# justfile — generated by justx · the justfile companion
# https://github.com/amberpixels/just-x
#
# Blocks between `# >>> justx:<id>` and `# <<< justx:<id>` are managed by justx.
# Edit anything outside the fences freely; `j @upgrade` (v2) re-syncs managed blocks.

# >>> justx:fmt (managed) — `j @upgrade` re-syncs; remove these fences to take over
# format shell scripts - rewrites to canonical form
fmt:
    shfmt -w -i 2 -ci .
# <<< justx:fmt

# >>> justx:lint (managed) — `j @upgrade` re-syncs; remove these fences to take over
# lint shell scripts - reports findings, changes nothing
lint:
    shfmt -f . | xargs -r shellcheck
    shfmt -d -i 2 -ci .
# <<< justx:lint

# >>> justx:fix (managed) — `j @upgrade` re-syncs; remove these fences to take over
# auto-fix what can be fixed - run on a clean tree and read the diff
fix:
    shfmt -f . | xargs -r shellcheck -f diff | git apply --allow-empty
    shfmt -w -s -i 2 -ci .
# <<< justx:fix

# >>> justx:ci (managed) — `j @upgrade` re-syncs; remove these fences to take over
# run all checks - read-only, safe for CI
ci: lint
# <<< justx:ci

# build the f10 binary
build:
    go build ./...

# install the f10 binary into GOBIN
install:
    go install ./cmd/f10

# lint Go code - standardgo owns the ruleset, no config file here
lint-go:
    go tool standardgo

# test Go packages, the resolve.sh parity suite included
test:
    go test ./...
